spring:
  kafka:
    bootstrap-server: "localhost:9092"
    consumer:
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        spring:
          json:
            value:
              default:
                type: "com.example.dispatch.message.OrderCreated"
